services:
  backend:
    build:
      context: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
    command: npm run server

  frontend:
    build:
      context: ./frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules # impede conflitos entre host e container
    environment:
      - NODE_ENV=development
    command: npm run dev

